name: "MySQL Server"
slug: mysql_addon
version: "1.0.2"
image: "mysql"
arch: [amd64, aarch64]
startup: services
boot: auto
ports:
  "3306/tcp": 3306
options:
  port: 3306
  root_password: "admin"
schema:
  port: port
  root_password: str
map:
  - data
