name: "MySQL Server"
description: "Custom MySQL server as Home Assistant add‑on"
version: "1.0.1"
slug: mysql_addon
url: "https://github.com/deepaksy/portfolio-addon"
arch:
  - amd64
  - aarch64
init: false
startup: services
boot: "auto"  # optional
ports:
  3306/tcp: "{{ port }}"
options:
  port: 3306
  root_password: "admin"
schema:
  port: int
  root_password: str
map:
  - data
  - addon_config:rw
backup: cold
# apparmor.txt: include for stricter security
