name: "MySQL Server"
description: "Custom MySQL server as Home Assistant add‑on"
version: "1.0.1"
slug: mysql_addon
url: "https://github.com/deepaksy/portfolio-addon"
arch:
  - amd64
  - aarch64
init: false
startup: services
boot: "auto"
ports:
  "3306/tcp": 3306
options:
  root_password: "admin"
schema:
  root_password: str
map:
  - data
backup: cold
