name: "Portfolio Backend App"
version: "1.0.0"
slug: portfolio-backend-app
description: "Custom Backend app"
arch:
  - amd64
  - arm64
startup: "application"
boot: "auto"
image: "deepaksy/portfolio-backend-app:latest"
ports:
  8000/tcp: 7987
options:
  debug: false
map:
  - type: addon_config
    read_only: false
options:
  db_user: ""
  db_pass: ""

schema:
  db_user: str
  db_pass: password

environment:
  DB_USER: !env_var db_user
  DB_PASS: !env_var db_pass
