name: "Portfolio Backend App"
version: "1.0.0"
slug: portfolio-backend-app
description: "Custom Backend app"
arch:
  - amd64
  - aarch64
startup: "application"
boot: "auto"
image: "ghcr.io/deepaksy/{arch}-portfolio-addon"
ports:
  8000/tcp: 7987
options:
  debug: false
schema:
  debug: bool
map:
  - config:rw

